theme: jekyll-theme-minimal
title: "Lior Neumann"
description: Security Researcher, Cryptographer and Machine Learning Enthusiast.
logo: img/face_blur_circle.png
use_logo: true
favicon: img/face_blur_circle.png
show_downloads: false
